draw_main_menu:-
  nl,nl,nl,nl,nl,nl,nl,nl,nl,nl,nl,nl,nl,nl,nl,nl,nl,nl,nl,nl,nl,nl,nl,nl,nl,nl,
  write('//=======================================================\\\\'), nl,
  write('||                                                       ||'), nl,
  write('||    _____                 _ _    _____ _               ||'), nl,
  write('||   / ____|               | | |  / ____| |              ||'), nl,
  write('||  | (___  _ __ ___   __ _| | | | (___ | |_ __ _ _ __   ||'), nl,
  write('||   \\___ \\| \'_ \` _ \\ / _\` | | |  \\___ \\| __/ _\` | \'__|  ||'), nl,
  write('||   ____) | | | | | | (_| | | |  ____) | || (_| | |     ||'), nl,
  write('||  |_____/|_| |_| |_|\\__,_|_|_| |_____/ \\__\\__,_|_|     ||'), nl,
  write('||                                                       ||'), nl,
  write('||                                                       ||'), nl,
  write('||    ') , write(' ______                 _                          ||'), nl,
  write('||    ') , write('|  ____|               (_)                         ||'), nl,
  write('||    ') , write('| |__   _ __ ___  _ __  _ _ __ ___  ___            ||'), nl,
  write('||    ') , write('|  __| | \'_ \` _ \\| \'_ \\| | \'__/ _ \\/ __|           ||'), nl,
  write('||    ') , write('| |____| | | | | | |_) | | | |  __/\\__ \\           ||'), nl,
  write('||    ') , write('|______|_| |_| |_| .__/|_|_|  \\___||___/           ||'), nl,
  write('||    ') , write('               | |                                 ||'), nl,
  write('||    ') , write('               |_|                                 ||'),  nl,
  write('||                                                       ||'), nl,
  write('||                                                       ||'), nl,
  write('||                                                       ||'), nl,
  write('||   Select an action:                                   ||'), nl,
  write('||                                                       ||'), nl,
  write('||   1 - Play: Human Versus Human                        ||'), nl,
  write('||   2 - Play: Human Versus Computer                     ||'), nl,
  write('||   3 - Play: Computer Versus Computer                  ||'), nl,
  write('||   4 - Exit                                            ||'), nl,
  write('||                                                       ||'), nl,
  write('\\\\=======================================================//'), nl,
  nl,nl,nl.
